config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get 'bookings', to: 'bookings#index'
  resources :bikes, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:update]
end

#if statement with bookings for renter bookings for bikes
# bookings.user
# bookings.bike

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  CATEGORIES = ['Road Bike', 'Cruiser', 'Fixed Gear', 'Mountain Bike', 'BMX',
                'Touring Bike', 'Recumbent Bike', 'Folding Bike', 'Utility Bike']
  BRAKES = ['Hand brake', 'Pedal brake', 'Hand and pedal brakes']
  AVAILABLE = ['available', 'not available']

  validates :brand, presence: true
  validates :price_per_day, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :brake_type, inclusion: { in: BRAKES }, allow_blank: true
  validates :number_of_gears, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true
  validates :status, inclusion: { in: AVAILABLE }, allow_blank: true
  validates :photo, presence: true
  validates :address, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bikes
  has_many :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

    before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def home
  end

  def index
    if params[:query].present?
      @bikes = policy_scope(Bike).near(params[:query], 10)
    else
      @bikes = policy_scope(Bike).order(created_at: :desc)
    end

    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bike: bike }),
        image_url: helpers.asset_url('bicycle.png')
      }
    end
  end

  def show
    @bike = Bike.find(params[:id])
    authorize @bike

    @markers =
    [{
      lat: @bike.latitude,
      lng: @bike.longitude,
      info_window: render_to_string(partial: "info_window", locals: { bike: @bike }),
      image_url: helpers.asset_url('bicycle.png')
    }]
    @booking = Booking.new
  end

  def new
    @bike = Bike.new
    authorize @bike
  end

  def create
    @bike = Bike.new(bike_params)
    authorize @bike
    @bike.user = current_user

    if @bike.save
      redirect_to bikes_path
    else
      render :new
    end
  end

  private

  def bike_params
    params.require(:bike).permit(:user_id, :category, :brand, :brake_type, :price_per_day, :status, :number_of_gears, :photo, :address, :description)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    # @list_bookings = Booking.all

    @bookings = policy_scope(Booking)

    @owner = current_user.bikes.any?
    @bookings_as_renter = current_user.bookings

    if @owner
      @my_bikes = current_user.bikes
      @bookings_as_owner = Booking.where(bike_id: @my_bikes.pluck(:id))
    end
  end

  def create
    @booking = Booking.new(start_date: Date.parse(booking_params[:start_date]), end_date: Date.parse(booking_params[:end_date]))
    authorize @booking
    @bike = Bike.find(params[:bike_id])
    @booking.user = current_user
    @booking.status = "pending"
    @booking.total_price = (Date.parse(booking_params[:end_date]) - Date.parse(booking_params[:start_date])).to_i * @bike.price_per_day

    @booking.bike = @bike
    if @booking.save
      redirect_to bikes_path
    else
      redirect_to bike_path(@bike)
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking

    if params[:query] == "accept"
      @booking.status = "accepted"
    end

    if params[:query] == "reject"
      @booking.status = "rejected"
    end

    @booking.save!

    redirect_to bookings_path
  end

private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def bookings
    # return the (array?) of bookings for a particular user
    # find by user id?
    # @booking.user = current_user
    current_user.bookings = Booking.find(params[:user_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home

  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<h6><%= bike.category %></h6>
<p><%= bike.address %></p>
<%= link_to bike_path(bike) do %>
<%= cl_image_tag bike.photo.key, style: 'height:100px;width:auto;' %>
<% end %>

app/views/bikes/index.html.erb
<div class="container mt-4 mb-4" id="green-letter">
  <h1>Have a look at the beautiful bikes we have to offer</h1>
</div>

<div class="container d-flex mb-4">
  <div class="container all-bikes">
    <div class="cards">
      <% @bikes.each do |bike| %>
        <%= link_to bike_path(bike) do %>
        <div class="card-trip">
          <% if bike.photo.attached? %>
          <%= cl_image_tag bike.photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
          <div class="card-trip-infos">
            <div>
              <h2><%= bike.category %></h2>
              <p>Brand: <%= bike.brand %></p>
              <% if bike.status == "available" %>
                <div class="d-flex align-items-center">
                  <p>  </p>
                  <i class="fas fa-circle" style="color: #99C2A2; font-size: 12px"></i>
                </div>
              <% else %>
                <div class="d-flex align-items-center">
                  <p>Current status  </p>
                  <i class="fas fa-circle" style="color: #ca3c25; font-size: 12px"></i>
                </div>
              <% end %>
            </div>
            <%= cl_image_tag bike.user.photo.key, crop: :fill, class:"card-trip-user avatar-bordered" %>
            <h2>€<%= bike.price_per_day %></h2>
          </div>
        </div>
        <% end %>
      <% end  %>
    </div>
  </div>

<!-- <div class = "container mb-4">
  <h2><em>Or pick a location</em></h2>
-->
  <div id="map"
  style="width: 50%"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
<!-- </div>
-->

app/views/bikes/new.html.erb
<header class="banner-new-bike">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
      </div>
    </div>
  </div>
</header>

<div class="container mt-4 mb-4" id="new-bike-form">
  <h3 style="text-align:center">Add your bike</h3>
  <h5 style="text-align:center" class="mb-2">(and earn money while sleeping)</h5>

  <%= simple_form_for(@bike) do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.input :price_per_day, label: "Price per day (EUR)", input_html: { min: '0'} %>
  <%= f.input :brand %>
  <%= f.input :address %>
  <%= f.input :category, :collection => Bike::CATEGORIES %>
  <%= f.input :brake_type, :collection => Bike::BRAKES %>
  <%= f.input :number_of_gears, input_html: { min: '0'} %>
  <%= f.input :status, :collection => Bike::AVAILABLE, as: :radio_buttons, :checked => Bike::AVAILABLE.first %>
  <%= f.button :submit, value: "Add Bike", class: "btn-green-filled" %>
  <% end %>
</div>

app/views/bikes/show.html.erb
<div class="container mt-4">
  <%= simple_form_for [@bike, @booking], html: {class: 'form-inline'} do |f| %>
  <%= f.input :start_date, as: :string, input_html: {class: "datepicker form-control mr-4"} %>
  <%= f.input :end_date, as: :string, input_html: {class: "datepicker form-control"} %>
  <%= f.submit "Book now", class: "btn btn-green-filled btn-green-smaller" %>
  <% end %>
</div>

<div class="container mt-2">
  <h3>Some information about this awesome bike</h3>

  <div class="container d-flex justify-content-between pl-0 pr-0 mt-4">
    <div class="card-bike mr-3">
     <div class="card-bike-show" style="background-image: url('<%= cl_image_path @bike.photo.key, crop: :fit %>')">
     </div>
      <!-- <img src="https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" /> -->
      <div class="card-bike-infos">
        <div>
          <h2><%= @bike.description %></h2>
          <p> <i class="fas fa-bicycle"></i> <%= @bike.category %></p>
          <p><i class="fas fa-tag"></i> Brand: <%= @bike.brand %></p>
          <p><i class="fas fa-circle" style="color: #99C2A2; font-size: 12px"></i> <%= @bike.status %></p>
          <p><i class="fas fa-cogs"></i> Number of gears: <%= @bike.number_of_gears %></p>
          <p><i class="fas fa-map-marked-alt"></i> <%= @bike.address %></p>
        </div>
        <div>
          <h2 class="card-bike-pricing"><%= @bike.price_per_day %>€ per day</h2>
          <!--  <button type="button" class="btn btn-success m-3">Book bike</button> -->
        </div>
      </div>
    </div>

    <div id="map"
      style="width: 100%; height: 722px"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

  <div class="mt-4 mb-4" >
    <%= link_to "Back to all bikes", bikes_path, class: "btn btn-green-dark" %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container d-flex">
  <div class="bookings-container">

    <div class="bookings-header">
      <h3>Your bikes for rent <i class="fas fa-user-alt"></i> <i class="fas fa-arrow-right"></i> <i class="fas fa-bicycle"></i></h3>
    </div>
    <% @bookings_as_owner.each do |booking| %>
    <div class="card-booking mb-4">
    <%= link_to bike_path(booking.bike) do %>
      <%= cl_image_tag booking.bike.photo.key, crop: :fill %>
  <% end %>
      <div class="card-booking-infos text-align-left">
        <div class="d-flex justify-content-between">
         <h2>€<%= booking.total_price %></h2>
         <% if booking.status == "accepted" %>
         <i class="fas fa-circle" id="status-bubble" style="color: #99C2A2; font-size: 20px"></i>
         <% elsif booking.status == "pending" %>
         <i class="fas fa-circle" id="status-bubble" style="color: orange; font-size: 20px"></i>
         <% else %>
         <i class="fas fa-circle" id="status-bubble" style="color: #ca3c25; font-size: 20px"></i>
         <% end %>
       </div>
       <h2>Dates: <%= booking.start_date %> - <%= booking.end_date %></h2>
       <p><i class="fas fa-map-marked-alt"></i> <%= booking.bike.address %></p>
       <%= cl_image_tag booking.user.photo.key, crop: :fill, class:"card-trip-user avatar-bordered", id: "booking-avatar" %>

       <div class="d-flex justify-content-end mt-1" id="booking-buttons">
        <%= link_to booking_path(booking, query: "accept"), method: :patch do %>
        <div class="btn btn-accept mr-1">Accept</div>
        <% end %>
        <%= link_to booking_path(booking, query: "reject"), method: :patch do %>
        <div class="btn btn-reject">Reject</div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

</div>

<div class="bookings-container">
  <div class="bookings-header">
    <h3>Your upcoming bookings <i class="fas fa-bicycle"></i> <i class="fas fa-arrow-right"></i> <i class="fas fa-user-alt"></i></h3>
  </div>
  <% @bookings_as_renter.each do |booking| %>
    <div class="card-booking mb-4">
   <%= link_to bike_path(booking.bike) do %>
      <%= cl_image_tag booking.bike.photo.key, crop: :fill %>
      <% end %>
      <div class="card-booking-infos text-align-left">
        <div class="d-flex justify-content-between">
         <h2>€<%= booking.total_price %></h2>
         <% if booking.status == "accepted" %>
         <i class="fas fa-circle" id="status-bubble" style="color: #99C2A2; font-size: 20px"></i>
         <% elsif booking.status == "pending" %>
         <i class="fas fa-circle" id="status-bubble" style="color: orange; font-size: 20px"></i>
         <% else %>
         <i class="fas fa-circle" id="status-bubble" style="color: #ca3c25; font-size: 20px"></i>
         <% end %>
       </div>
       <h2>Dates: <%= booking.start_date %> - <%= booking.end_date %></h2>
       <p><i class="fas fa-map-marked-alt"></i> <%= booking.bike.address %></p>
       <%= cl_image_tag booking.bike.user.photo.key, crop: :fill, class:"card-trip-user avatar-bordered", id: "booking-avatar" %>
     </div>
   </div>
 <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<%# This is where all components are put together to make the app %>

<!DOCTYPE html>
<html>
  <head>
    <title>BikeBNB | Bike rentals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class='main-container'>
      <%= render "shared/navbar"%>
      <%= yield %>
      <%# We might want to change the spot of this sweet code %>
<!--        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p> -->
       
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%# This is the landing page, the code below does the following:
 banner image
 banner text
 insert registration button %>

 <header class="landing-banner">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-left">
        <h1>
          <span id="banner-typed-text" style="color: white" class="font-weight-light"></span>
        </h1>
        <p class="lead">Rent or lease <strong>bikes</strong> in just 3 clicks</p>

          <div>
             <%= form_tag bikes_path, id: "search-bar", method: :get do %>
              <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Type a city to start your search",
                  id: "bike_address"
                   %>
                  <%= submit_tag "Search", class: "btn btn-green mt-3" %>
             <% end %>
         <!--  </div>
        <% if user_signed_in? %>
          <%= link_to "Rent a bike", bikes_path, class: "btn btn-success mt-2" %>
        <% else %>
          <%= link_to "Register now", new_user_registration_path, class: "btn btn-success mt-2" %>
        <% end %>
      </div> -->
    </div>
  </div>
</header>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container d-flex justify-content-between">
    <div class="footer-links">
      <ul>
        <li>Follow us </li>
        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
        <li><a href="#"><i class="fab fa-facebook"></i></a></li>
      </ul>
    </div>
    <div class="footer-copyright">
      The best bikes in the world <i class="fas fa-biking"></i>
      <br>
      <h6>®BikeBNB. All rights reserved.</h6>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-static-top navbar-light navbar-lewagon">

    <div class="container">
        <%= link_to root_path, class: "navbar-brand" do %>
        <div class="bicycle-logo">
          <i class="fas fa-bicycle"></i>
        </div>
        <% end %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
                <div>
                  <li class="nav-item">
                    <%= link_to "Bikes for rent", bikes_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Add your bike", new_bike_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Bookings", bookings_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <h6>|</h6>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                  </li>
                </div>
            <% else %>
                <li class="nav-item">
                  <%= link_to "Bikes for rent", bikes_path, class: "nav-link" %>
                </li>
                <div>
                  <li class="nav-item">
                    <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Register",  new_user_registration_path, class: "nav-link" %>
                  </li>
                  </div>
            <% end %>
          </ul>
        </div>
    </div>
</nav>